# SETTINGS
# GENERAL
general:
  data:
    path: ./../datasets/breast_cancer
    type: csv
# DATA UNDERSTANDING
data_understanding:
  description:
    execute: True
    name: breast_cancer
    include: all
  plots:
    execute: False
    histograms:
      execute: True
      columns: -1
      label: y
      format: png
    boxplots:
      execute: False
      columns: -1
# DATA PREPARATION
data_preparation:
  data_split:
    execute: True
    validation_set: False
    label: y
    split:
      - 0.8
      - 0.2
    seed: None
# MODELING
modeling:
  classification:
    execute: False
    classifiers:
      - knn
# EVALUATION
evaluation:
